files:
  - source: /
    destination: /home/ubuntu/webbuild
permissions:
  - object: /home/ubuntu/webbuild
    pattern: "*.dll"
    mode: 777
hooks: 
  BeforeInstall:
    - location: /install-deps.sh
      timeout: 900
      runas: root
os: linux
version: 0.0